# Generated by Django 4.1.6 on 2023-02-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='ValueForInput',
        ),
    ]
